name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Bump version
        run: npm version ${{ github.event.inputs.bump }} --no-git-tag-version

      - name: Read new version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: bump version to ${{ steps.version.outputs.version }}'
          branch: 'bump-version/${{ steps.version.outputs.version }}'
          title: 'chore: bump version to ${{ steps.version.outputs.version }}'
          body: 'Automated version bump to `${{ steps.version.outputs.version }}` (${{ github.event.inputs.bump }}).'
          delete-branch: true
